version: '3.8'

services:
  person-api:
    build: .
    container_name: person-api
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=development
      - PORT=3004
      - CORE_CLIENT_ID=CORE-API
      - CORE_CLIENT_SECRET=bf72c1ce-213b-4efb-9c62-ae552d7ac445
    volumes:
      - .:/app
      - /app/node_modules
