apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
        - name: person-api
          image: person-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: CORE_CLIENT_ID
              value: CORE-API
            - name: CORE_CLIENT_SECRET
              value: bf72c1ce-213b-4efb-9c62-ae552d7ac445
---
apiVersion: v1
kind: Service
metadata:
  name: person-api-service
spec:
  selector:
    app: person-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
  type: LoadBalancer
